#-------------------------------------------------------------------------
# Created: Mon Mar 25 11:54:44 2013 by /afs/naf.desy.de/user/m/marconi/scratch/SingleTau/ntupleProducer/CMSSW_5_3_7_patch4/src/VBFntupleProducer/VBFntupleProducer/python/test_Tau_cfi.py
#-------------------------------------------------------------------------
import FWCore.ParameterSet.Config as cms
demo =\
cms.EDAnalyzer("TheNtupleMaker",
               ntupleName = cms.untracked.string("ntuple.root"),
               analyzerName = cms.untracked.string("analyzer.cc"),

               buffers =
               cms.untracked.
               vstring(
    'patTau'
    ),
               patTau =
               cms.untracked.
               vstring(
    'patTau                          patTaus                         200',
    #---------------------------------------------------------------------
    'int  charge()',
    'double  p()',
    'double  energy()',
    'double  et()',
    'double  px()',
    'double  py()',
    'double  pz()',
    'double  pt()',
    'double  phi()',
    'double  eta()',
    'float  tauID("byIsolationMVAraw") tauID_byIsolationMVAraw',
    'float  tauID("byMediumCombinedIsolationDeltaBetaCorr") tauID_byMediumCombinedIsolationDeltaBetaCorr',
    'float  tauID("byCombinedIsolationDeltaBetaCorrRaw3Hits") tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits',
    'float  tauID("againstMuonMedium") tauID_againstMuonMedium',
    'float  tauID("againstElectronTightMVA3") tauID_againstElectronTightMVA3',
    'float  tauID("againstElectronTightMVA2") tauID_againstElectronTightMVA2',
    'float  tauID("byLooseIsolationMVA2") tauID_byLooseIsolationMVA2',
    'float  tauID("againstMuonTight") tauID_againstMuonTight',
    'float  tauID("againstMuonLoose2") tauID_againstMuonLoose2',
    'float  tauID("byTightIsolationMVA") tauID_byTightIsolationMVA',
    'float  tauID("byLooseIsolation") tauID_byLooseIsolation',
    'float  tauID("byLooseCombinedIsolationDeltaBetaCorr") tauID_byLooseCombinedIsolationDeltaBetaCorr',
    'float  tauID("againstElectronLooseMVA3") tauID_againstElectronLooseMVA3',
    'float  tauID("againstElectronLooseMVA2") tauID_againstElectronLooseMVA2',
    'float  tauID("againstElectronTight") tauID_againstElectronTight',
    'float  tauID("byVLooseCombinedIsolationDeltaBetaCorr") tauID_byVLooseCombinedIsolationDeltaBetaCorr',
    'float  tauID("againstElectronVTightMVA3") tauID_againstElectronVTightMVA3',
    'float  tauID("againstElectronMediumMVA3") tauID_againstElectronMediumMVA3',
    'float  tauID("againstElectronMediumMVA2") tauID_againstElectronMediumMVA2',
    'float  tauID("againstElectronMVA") tauID_againstElectronMVA',
    'float  tauID("againstMuonLoose") tauID_againstMuonLoose',
    'float  tauID("againstMuonTight2") tauID_againstMuonTight2',
    'float  tauID("againstElectronMedium") tauID_againstElectronMedium',
    'float  tauID("againstElectronVLooseMVA2") tauID_againstElectronVLooseMVA2',
    'float  tauID("againstMuonMedium2") tauID_againstMuonMedium2',
    'float  tauID("byMediumIsolationMVA") tauID_byMediumIsolationMVA',
    'float  tauID("byMediumCombinedIsolationDeltaBetaCorr3Hits") tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits',
    'float  tauID("byLooseIsolationDeltaBetaCorr") tauID_byLooseIsolationDeltaBetaCorr',
    'float  tauID("byIsolationMVA2raw") tauID_byIsolationMVA2raw',
    'float  tauID("byTightIsolationMVA2") tauID_byTightIsolationMVA2',
    'float  tauID("againstElectronMVA2category") tauID_againstElectronMVA2category',
    'float  tauID("byTightIsolationDeltaBetaCorr") tauID_byTightIsolationDeltaBetaCorr',
    'float  tauID("againstElectronDeadECAL") tauID_againstElectronDeadECAL',
    'float  tauID("againstElectronMVA3category") tauID_againstElectronMVA3category',
    'float  tauID("byVLooseIsolationDeltaBetaCorr") tauID_byVLooseIsolationDeltaBetaCorr',
    'float  tauID("againstElectronMVA2raw") tauID_againstElectronMVA2raw',
    'float  tauID("byTightCombinedIsolationDeltaBetaCorr") tauID_byTightCombinedIsolationDeltaBetaCorr',
    'float  tauID("againstElectronMVA3raw") tauID_againstElectronMVA3raw',
    'float  tauID("byLooseCombinedIsolationDeltaBetaCorr3Hits") tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits',
    'float  tauID("byMediumIsolationMVA2") tauID_byMediumIsolationMVA2',
    'float  tauID("byMediumIsolationDeltaBetaCorr") tauID_byMediumIsolationDeltaBetaCorr',
    'float  tauID("againstElectronLoose") tauID_againstElectronLoose',
    'float  tauID("byTightIsolation") tauID_byTightIsolation',
    'float  tauID("byVLooseIsolation") tauID_byVLooseIsolation',
    'float  tauID("byLooseIsolationMVA") tauID_byLooseIsolationMVA',
    'float  tauID("byCombinedIsolationDeltaBetaCorrRaw") tauID_byCombinedIsolationDeltaBetaCorrRaw',
    'float  tauID("byTightCombinedIsolationDeltaBetaCorr3Hits") tauID_byTightCombinedIsolationDeltaBetaCorr3Hits',
    'float  tauID("decayModeFinding") tauID_decayModeFinding',
    'float  tauID("byMediumIsolation") tauID_byMediumIsolation',
    'double  leadPFChargedHadrCand()->p()',
    'double  leadPFChargedHadrCand()->energy()',
    'double  leadPFChargedHadrCand()->et()',
    'double  leadPFChargedHadrCand()->mass()',
    'double  leadPFChargedHadrCand()->massSqr()',
    'double  leadPFChargedHadrCand()->mt()',
    'double  leadPFChargedHadrCand()->mtSqr()',
    'double  leadPFChargedHadrCand()->px()',
    'double  leadPFChargedHadrCand()->py()',
    'double  leadPFChargedHadrCand()->pz()',
    'double  leadPFChargedHadrCand()->pt()',
    'double  leadPFChargedHadrCand()->phi()',
    'double  leadPFChargedHadrCand()->theta()',
    'double  leadPFChargedHadrCand()->eta()',
    'double  leadPFChargedHadrCand()->rapidity()',
    'double  leadPFChargedHadrCand()->y()',
    #'size_t  signalPFChargedHadrCands().size()'
    )
               )
